### ISSUE TITLE
math.round does not exist.

### ISSUE THREAD

**Issue by Lightnet** [nekromoff/layouter#2]
I check the doc that function does not exist for love2D. Unless I am wrong.

**Comment by nekromoff** [comment]
Ah, good catch. Sorry about that, I have this function in my helpers.lua file and use it widely.

I'll add it to layouter, but in the meantime you can just add this yourself:
```
function math.round(num, numDecimalPlaces)
    local mult = 10 ^ (numDecimalPlaces or 0)
    return math.floor(num * mult + 0.5) / mult
end
```

**Comment by nekromoff** [comment]
Fixed in https://github.com/nekromoff/layouter/commit/cba040e679de7387447eed7c485c00adc706815d
